import hbv_vimc as hbv
import at_tools
import sciris as sc

s_yr = 1990  # start year
e_yr = 2101  # update code so actual year can be used
dt = 0.25

uncert = False
runs = 200

fw = hbv.root/"frameworks"/"hbv_v15_dev.xlsx"
settings = at_tools.ProjectConfig.from_yaml(hbv.root / "frameworks" / "model_config_hbv.yaml")
settings.update_time_vector(start=s_yr, end=e_yr, dt=dt)

settings_b = at_tools.ProjectConfig.from_yaml(hbv.root / "frameworks" / "model_config_hbv_a.yaml")
settings_b.update_time_vector(start=s_yr, end=e_yr, dt=dt)

regions = sc.odict({
    'AFR': 'African Region',
    'AMR': 'Region of the Americas',
    'EMR': 'Eastern Mediterranean Region',
    'EUR': 'European Region',
    'SEAR': 'South-East Asia Region',
    'WPR': 'Western Pacific Region',
})

countries = sc.odict({
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHR': 'Bahrain',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia, Plurinational State Of',
    'BRA': 'Brazil',
    'BTN': 'Bhutan',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': "Côte d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Congo, The Democratic Republic of the',
    'COG': 'Congo',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cabo Verde',
    'CRI': 'Costa Rica',
    'CUB': 'Cuba',
    'CZE': 'Czech Republic',
    'DEU': 'Germany',
    'DJI': 'Djibouti',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIN': 'Finland',
    'FJI': 'Fiji',
    'FRA': 'France',
    'FSM': 'Micronesia, Federated States of',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'Gambia',
    'GNB': 'Guinea-Bissau',
    'GRC': 'Greece',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HTI': 'Haiti',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Ireland',
    'IRN': 'Iran, Islamic Republic of',
    'IRQ': 'Iraq',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KOR': 'Korea, Republic of',
    'KWT': 'Kuwait',
    'LAO': "Lao People's Democratic Republic",
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'MAR': 'Morocco',
    'MDA': 'Moldova, Republic of',
    'MDG': 'Madagascar',
    'MEX': 'Mexico',
    'MKD': 'Macedonia, The Former Yugoslav Republic of',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NPL': 'Nepal',
    'NZL': 'New Zealand',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRK': "Korea, Democratic People's Republic of",
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'QAT': 'Qatar',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SGP': 'Singapore',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SOM': 'Somalia',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'STP': 'Sao Tome and Principe',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Swaziland',
    'SYR': 'Syrian Arab Republic',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TZA': 'Tanzania, United Republic of',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VEN': 'Venezuela, Bolivarian Republic of',
    'VNM': 'Viet Nam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'YEM': 'Yemen',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe',
})

vimc = sc.odict({
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'ARM': 'Armenia',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia, Plurinational State of',
    'BTN': 'Bhutan',
    'CAF': 'Central African Republic',
    'CHN': 'China',
    'CIV': "Cote d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Congo, the Democratic Republic of the',
    'COG': 'Congo',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cabo Verde',
    'CUB': 'Cuba',
    'DJI': 'Djibouti',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ETH': 'Ethiopia',
    'FJI': 'Fiji',
    'FSM': 'Micronesia, Federated States of',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'Gambia',
    'GNB': 'Guinea-Bissau',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HND': 'Honduras',
    'HTI': 'Haiti',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRN': 'Iran, Islamic Republic of',
    'IRQ': 'Iraq',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'LAO': "Lao People's Democratic Republic",
    'LBR': 'Liberia',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'MAR': 'Morocco',
    'MDA': 'Moldova, Republic of',
    'MDG': 'Madagascar',
    'MKD': 'Macedonia, the former Yugoslav Republic of',
    'MLI': 'Mali',
    'MMR': 'Myanmar',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MWI': 'Malawi',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NPL': 'Nepal',
    'PAK': 'Pakistan',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PNG': 'Papua New Guinea',
    'PRK': "Korea, Democratic People's Republic of",
    'PRY': 'Paraguay',
    'RWA': 'Rwanda',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SOM': 'Somalia',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'STP': 'Sao Tome and Principe',
    'SWZ': 'Swaziland',
    'SYR': 'Syrian Arab Republic',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TUN': 'Tunisia',
    'TZA': 'Tanzania, United Republic of',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'UZB': 'Uzbekistan',
    'VEN': 'Venezuela, Bolivarian Republic of',
    'VNM': 'Viet Nam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'YEM': 'Yemen',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe',
    'DMA': 'Domenica',
    'GRD': 'Grenada',
    'LCA': 'Saint Lucia',
    'MDV': 'Maldives',
    'MHL': 'Marshall Islands',
    'NAM': 'Namibia',
    'PSE': 'Palestine, State of',
    'TUV': 'Tuvalu',
    'VCT': 'Saint Vincent and the Grenadines',
    'XK': 'Kosovo'
})

missing = sc.odict({'DMA': 'Domenica',
                    'GRD': 'Grenada',
                    'LCA': 'Saint Lucia',
                    'MDV': 'Maldives',
                    'MHL': 'Marshall Islands',
                    'NAM': 'Namibia',
                    'PSE': 'Palestine, State of',
                    'TUV': 'Tuvalu',
                    'VCT': 'Saint Vincent and the Grenadines',
                    'XK': 'Kosovo'})


develop = sc.odict({'CHN': 'China',
                    'IND': 'India',
                    'IDN': 'Indonesia',
                    'NGA': 'Nigeria',
                    'EGY': 'Egypt',
                    'PAK': 'Pakistan',
                    'THA': 'Thailand',
                    'BGD': 'Bangladesh',
                    'VNM': 'Viet Nam',
                    'MMR': 'Myanmar',
                    'ETH': 'Ethiopia',
                    'PHL': 'Philippines',
                    'COD': 'Congo, The Democratic Republic of the'})

country_to_region = sc.odict({ 
    'AFG': 'EMR', 'AGO': 'AFR', 'ALB': 'EUR', 'ARM': 'EUR', 'AZE': 'EUR',  
    'BDI': 'AFR', 'BEN': 'AFR', 'BFA': 'AFR', 'BGD': 'SEAR', 'BIH': 'EUR',  
    'BLR': 'EUR', 'BLZ': 'AMR', 'BOL': 'AMR', 'BTN': 'SEAR', 'CAF': 'AFR',  
    'CHN': 'WPR', 'CIV': 'AFR', 'CMR': 'AFR', 'COD': 'AFR', 'COG': 'AFR',  
    'COL': 'AMR', 'COM': 'AFR', 'CPV': 'AFR', 'CUB': 'AMR', 'DJI': 'EMR',  
    'DZA': 'AFR', 'ECU': 'AMR', 'EGY': 'EMR', 'ERI': 'AFR', 'ETH': 'AFR',  
    'FJI': 'WPR', 'FSM': 'WPR', 'GEO': 'EUR', 'GHA': 'AFR', 'GIN': 'AFR',  
    'GMB': 'AFR', 'GNB': 'AFR', 'GTM': 'AMR', 'GUY': 'AMR', 'HND': 'AMR',  
    'HTI': 'AMR', 'IDN': 'SEAR', 'IND': 'SEAR', 'IRN': 'EMR', 'IRQ': 'EMR',  
    'JAM': 'AMR', 'JOR': 'EMR', 'KEN': 'AFR', 'KGZ': 'EUR', 'KHM': 'WPR',  
    'KIR': 'WPR', 'LAO': 'WPR', 'LBR': 'AFR', 'LKA': 'SEAR', 'LSO': 'AFR',  
    'MAR': 'EMR', 'MDA': 'EUR', 'MDG': 'AFR', 'MKD': 'EUR', 'MLI': 'AFR',  
    'MMR': 'SEAR', 'MNG': 'WPR', 'MOZ': 'AFR', 'MRT': 'AFR', 'MWI': 'AFR',  
    'NER': 'AFR', 'NGA': 'AFR', 'NIC': 'AMR', 'NPL': 'SEAR', 'PAK': 'EMR',  
    'PER': 'AMR', 'PHL': 'WPR', 'PNG': 'WPR', 'PRK': 'WPR', 'PRY': 'AMR',  
    'RWA': 'AFR', 'SDN': 'EMR', 'SEN': 'AFR', 'SLB': 'WPR', 'SLE': 'AFR',  
    'SLV': 'AMR', 'SOM': 'AFR', 'SRB': 'EUR', 'SSD': 'AFR', 'STP': 'AFR',  
    'SWZ': 'AFR', 'SYR': 'EMR', 'TCD': 'AFR', 'TGO': 'AFR', 'THA': 'SEAR',  
    'TJK': 'EUR', 'TKM': 'EUR', 'TLS': 'SEAR', 'TON': 'WPR', 'TUN': 'EMR',  
    'TZA': 'AFR', 'UGA': 'AFR', 'UKR': 'EUR', 'UZB': 'EUR', 'VEN': 'AMR',  
    'VNM': 'WPR', 'VUT': 'WPR', 'WSM': 'WPR', 'YEM': 'EMR', 'ZAF': 'AFR',  
    'ZMB': 'AFR', 'ZWE': 'AFR'})


locations = regions + countries # All possible locations